syntax = "proto3";

package ru.nstu.isma.contracts.simulation;

import "simulation/simulation_method_item.proto";

option csharp_namespace = "Isma.Contracts.Simulation";
option go_package = "github.com/isma/contracts/simulation";
option java_multiple_files = true;
option java_package = "ru.nstu.isma.contracts.simulation";

/* 
 * Response containing list of available integration methods.
 */
message ListSimulationMethodsResponse {
  // List of available methods
  repeated SimulationMethodItem methods = 1;
}
