module isma.server.app {
    requires kotlin.stdlib;
    requires kotlin.reflect;
    requires koin.core.jvm;
    requires org.slf4j;
    requires ch.qos.logback.classic;
    requires ch.qos.logback.core;
    requires io.grpc.netty;
    requires io.grpc.stub;
    requires io.grpc.protobuf;
    requires io.grpc;
    requires io.grpc.services;
    requires com.google.protobuf;
    requires com.google.common;
    requires io.netty.buffer;
    requires io.netty.codec;
    requires io.netty.codec.compression;
    requires io.netty.common;
    requires io.netty.handler;
    requires io.netty.resolver;
    requires io.netty.transport;
    requires io.netty.transport.classes.epoll;
    requires io.netty.transport.epoll.linux.x86_64;
    requires io.netty.transport.unix.common;
    requires io.ktor.server.core;
    requires io.ktor.server.cio;
    requires io.ktor.server.content.negotiation;
    requires kotlinx.coroutines.core;
    requires kotlinx.io.bytestring;
    requires kotlinx.io.core;
    requires kotlinx.serialization.core;
    requires isma.server.domain;
    requires isma.server.infrastructure;
    requires isma.server.grpc;

    exports ru.nstu.isma.server.app;
    exports ru.nstu.isma.server.app.grpc;
    exports ru.nstu.isma.server.app.http;
}
